# Generated by Django 4.2 on 2023-07-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimental_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('arms_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('license_type', models.CharField(max_length=200)),
                ('arm_source', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('archive_reason', models.CharField(max_length=200)),
            ],
        ),
    ]
