# Generated by Django 4.2 on 2023-07-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_type', models.CharField(max_length=200, verbose_name=(('revolver', 'Revolver'), ('pistol', 'Pistol'), ('holster', 'Holster'), ('machine_gun', 'Machine Gun'), ('shot_gun', 'Shot Gun'), ('rifle', 'Rifle'), ('air_gun', 'Air Gun'), ('grenade_launcher', 'Grenade Launcher'), ('smg', 'SMG'), ('lmg', 'LMG'), ('mortar', 'Mortar'), ('craft_gun', 'Craft Gun'), ('sniper_rifle', 'Sniper Rifle')))),
                ('arm_action', models.CharField(max_length=200, verbose_name=(('semi_auto', 'Semi Automatic'), ('lever_action', 'Lever Action'), ('fully_automatic', 'Fully Automatic'), ('close_bolt', 'Close Bolt'), ('break_action', 'Break Action'), ('revolver', 'Revolver'), ('pistol_single_shot', 'Pistol Single Shot'), ('gas_operated', 'Gas Operated'), ('open_bolt', 'Open Bolt'), ('brech_load', 'Brech Load'), ('single_shot', 'Single Shot'), ('artillery', 'Artillery'), ('gas_regulated', 'Gas Regulated')))),
                ('arm_status', models.CharField(max_length=200, verbose_name=(('damaged', 'Damaged'), ('lost', 'Lost'), ('misplaced', 'Misplaced'), ('serviceable', 'Serviceable'), ('unserviceable', 'Unserviceable'), ('held_for_destruction', 'Held For Destruction'), ('destroyed', 'Destroyed'), ('return', 'Return'), ('registered', 'Registered')))),
                ('license_category', models.CharField(max_length=200, verbose_name=(('long_arm', 'Long Arm'), ('handgun', 'Handgun'), ('sport_shooting', 'Sport Shooting'), ('hunting', 'Hunting')))),
                ('genuine_reason', models.CharField(max_length=200, verbose_name=(('rfmf_personnel', 'RFMF Personnel'), ('navy_personnel', 'Navy Personnel'), ('police_personnel', 'Police Personnel'), ('civillian_personnel', 'Civillian Personnel')))),
                ('regimental_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200, verbose_name=(('major_general', 'Major General'), ('rear_admiral', 'Rear Admiral'), ('brigadier', 'Brigadier'), ('commodore', 'Commodore'), ('colonel', 'Colonel'), ('lt_colonel', 'LT Colonel'), ('major', 'Major'), ('chief_of_navy', 'Chief of Navy'), ('padre', 'Padre'), ('captain', 'Captain'), ('commander', 'Commander'), ('lt_commander', 'LT Commander'), ('leutenant ', 'Leutenant'), ('sub_leutenant', 'Sub Leutenant'), ('ensign', 'Ensign'), ('midshipman', 'Midshipman'), ('cadet', 'Cadet'), ('warrant_officer_I', 'Warrant Officer I'), ('warrant_officer_II', 'Warrant Officer II'), ('staff_sergeant', 'Staff Sergeant'), ('sergeant', 'Sergeant'), ('corporal', 'Corporal'), ('lance_corporal', 'Lance Corporal'), ('private', 'Private'), ('leutenant ', 'Leutenant'), ('rsm_army', 'RSM Army'), ('master_arm_navy', 'Master at Arm Navy'), ('ordinary_seaman', 'Ordinary Seaman Navy')))),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('unit', models.CharField(max_length=200)),
                ('ammunition_status', models.CharField(blank=True, choices=[('damage', 'Damage'), ('dispose', 'Dispose'), ('expended', 'Expended'), ('issue', 'Issue'), ('returned', 'Returned'), ('expired', 'Expired')], max_length=50)),
                ('license_type', models.CharField(max_length=200)),
                ('arm_source', models.CharField(max_length=200, verbose_name=(('confiscated', 'Confiscated'), ('previously_unregistered', 'Previously Unregistered'), ('surrendered', 'Surrendered'), ('imported', 'Imported')))),
                ('location', models.CharField(max_length=200, verbose_name=(('engineers', 'Engineers [Nabuni]'), ('ftg_nasinu', 'FTG Nasinu'), ('lsu_qeb_nabua', 'LSU QEB Nabua'), ('3fir_qeb_nabua', '3 FIR QEB Nabua'), ('naval_base_walubay', 'Naval Base Walubay'), ('togalevu_naval_base', 'Togalevu Naval Base'), ('lautoka', 'Lautoka Echo'), ('nadi', 'Nadi Delta'), ('black_rock', 'Black Rock'), ('labasa', 'Labasa Golf')))),
                ('archive_reason', models.CharField(max_length=200)),
                ('id_types', models.CharField(max_length=200, verbose_name=(('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('rfmf_id', 'RFMF ID'), ('police_id', 'Police ID')))),
            ],
        ),
        migrations.DeleteModel(
            name='Arms',
        ),
    ]
