# Generated by Django 4.2 on 2023-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_arm_delete_arms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='arm_action',
            field=models.CharField(choices=[('semi_auto', 'Semi Automatic'), ('lever_action', 'Lever Action'), ('fully_automatic', 'Fully Automatic'), ('close_bolt', 'Close Bolt'), ('break_action', 'Break Action'), ('revolver', 'Revolver'), ('pistol_single_shot', 'Pistol Single Shot'), ('gas_operated', 'Gas Operated'), ('open_bolt', 'Open Bolt'), ('brech_load', 'Brech Load'), ('single_shot', 'Single Shot'), ('artillery', 'Artillery'), ('gas_regulated', 'Gas Regulated')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='arm_source',
            field=models.CharField(choices=[('confiscated', 'Confiscated'), ('previously_unregistered', 'Previously Unregistered'), ('surrendered', 'Surrendered'), ('imported', 'Imported')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='arm_status',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('lost', 'Lost'), ('misplaced', 'Misplaced'), ('serviceable', 'Serviceable'), ('unserviceable', 'Unserviceable'), ('held_for_destruction', 'Held For Destruction'), ('destroyed', 'Destroyed'), ('return', 'Return'), ('registered', 'Registered')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='arm_type',
            field=models.CharField(choices=[('revolver', 'Revolver'), ('pistol', 'Pistol'), ('holster', 'Holster'), ('machine_gun', 'Machine Gun'), ('shot_gun', 'Shot Gun'), ('rifle', 'Rifle'), ('air_gun', 'Air Gun'), ('grenade_launcher', 'Grenade Launcher'), ('smg', 'SMG'), ('lmg', 'LMG'), ('mortar', 'Mortar'), ('craft_gun', 'Craft Gun'), ('sniper_rifle', 'Sniper Rifle')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='genuine_reason',
            field=models.CharField(choices=[('rfmf_personnel', 'RFMF Personnel'), ('navy_personnel', 'Navy Personnel'), ('police_personnel', 'Police Personnel'), ('civillian_personnel', 'Civillian Personnel')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='id_types',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('rfmf_id', 'RFMF ID'), ('police_id', 'Police ID')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='license_category',
            field=models.CharField(choices=[('long_arm', 'Long Arm'), ('handgun', 'Handgun'), ('sport_shooting', 'Sport Shooting'), ('hunting', 'Hunting')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='location',
            field=models.CharField(choices=[('engineers', 'Engineers [Nabuni]'), ('ftg_nasinu', 'FTG Nasinu'), ('lsu_qeb_nabua', 'LSU QEB Nabua'), ('3fir_qeb_nabua', '3 FIR QEB Nabua'), ('naval_base_walubay', 'Naval Base Walubay'), ('togalevu_naval_base', 'Togalevu Naval Base'), ('lautoka', 'Lautoka Echo'), ('nadi', 'Nadi Delta'), ('black_rock', 'Black Rock'), ('labasa', 'Labasa Golf')], max_length=200),
        ),
        migrations.AlterField(
            model_name='arm',
            name='rank',
            field=models.CharField(choices=[('major_general', 'Major General'), ('rear_admiral', 'Rear Admiral'), ('brigadier', 'Brigadier'), ('commodore', 'Commodore'), ('colonel', 'Colonel'), ('lt_colonel', 'LT Colonel'), ('major', 'Major'), ('chief_of_navy', 'Chief of Navy'), ('padre', 'Padre'), ('captain', 'Captain'), ('commander', 'Commander'), ('lt_commander', 'LT Commander'), ('leutenant ', 'Leutenant'), ('sub_leutenant', 'Sub Leutenant'), ('ensign', 'Ensign'), ('midshipman', 'Midshipman'), ('cadet', 'Cadet'), ('warrant_officer_I', 'Warrant Officer I'), ('warrant_officer_II', 'Warrant Officer II'), ('staff_sergeant', 'Staff Sergeant'), ('sergeant', 'Sergeant'), ('corporal', 'Corporal'), ('lance_corporal', 'Lance Corporal'), ('private', 'Private'), ('leutenant ', 'Leutenant'), ('rsm_army', 'RSM Army'), ('master_arm_navy', 'Master at Arm Navy'), ('ordinary_seaman', 'Ordinary Seaman Navy')], max_length=200),
        ),
    ]
